package com.fc.v2.mapper.message;

import com.fc.v2.model.message.UserMessageTrainRecord;
import com.fc.v2.model.message.UserMessageTrainRecordExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserMessageTrainRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_train_record
     *
     * @mbg.generated
     */
    long countByExample(UserMessageTrainRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_train_record
     *
     * @mbg.generated
     */
    int deleteByExample(UserMessageTrainRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_train_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_train_record
     *
     * @mbg.generated
     */
    Long insert(UserMessageTrainRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_train_record
     *
     * @mbg.generated
     */
    int insertSelective(UserMessageTrainRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_train_record
     *
     * @mbg.generated
     */
    List<UserMessageTrainRecord> selectByExample(UserMessageTrainRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_train_record
     *
     * @mbg.generated
     */
    UserMessageTrainRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_train_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserMessageTrainRecord record, @Param("example") UserMessageTrainRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_train_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserMessageTrainRecord record, @Param("example") UserMessageTrainRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_train_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserMessageTrainRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_train_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserMessageTrainRecord record);

    /**
     * 根据userid查询对应记录
     * @Author cgy
     * @Date 15:42 2023/5/23
     * @Param
     * @param userId
     * @return
     * @return java.util.List<com.fc.v2.model.message.UserMessageTrainRecord>
     **/
    UserMessageTrainRecord getByUserId(Long userId);
}