package com.fc.v2.mapper.message;

import com.fc.v2.model.message.UserMessageHistory;
import com.fc.v2.model.message.UserMessageHistoryExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository
public interface UserMessageHistoryMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_history
     *
     * @mbg.generated
     */
    Long insert(UserMessageHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_history
     *
     * @mbg.generated
     */
    int insertSelective(UserMessageHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_history
     *
     * @mbg.generated
     */
    UserMessageHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserMessageHistory record, @Param("example") UserMessageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserMessageHistory record, @Param("example") UserMessageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserMessageHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table us_message_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserMessageHistory record);

    /**
     * 根据userId获取对应数据
     * @Author cgy
     * @Date 14:16 2023/5/19
     * @Param
     * @param userId
     * @return
     * @return java.util.List<com.fc.v2.model.message.UserMessageHistory>
     **/
    List<UserMessageHistory> getByUserId(Long userId);
}