# 项目相关配置
fuce:
  #名称
  name: v2
  #版本
  version: 4.2
  #版权年份
  copyright-year: 2018
  #邮件功能
  #邮箱发送smtp
  email-smtp: smtp.sina.com
  #邮箱发送端口
  email-port: 465
  #发送邮箱登录账号
  email-account: 1@sina.com
  #发送邮箱登录密码
  email-password: f1
  #实例演示开关 启动该模式删除增加修改会弹出演示模式提示框
  demo-enabled: false
  #漂亮得拖动验证码 默认false普通验证码、true滚动验证码
  roll-verification: false
  #xss不拦截url
  xss-not-filter-url: [/api/v1/token/api_token,/api/v1/yibaotong/save]
  #shiro不拦截url
  sa-token-not-filter-url: [/api/v1/token/api_token,/api/v1/yibaotong/save]
#tomcat config
server :
  port : 8080
  ##项目名字配置
  #servlet :
  #  context-path : /demo
  tomcat :
    uri-encoding : UTF-8
    #xx 报错修改的地方
    max-connections: 200000
    max-http-form-post-size: 9000000
    threads:
      max: 128
      min-spare: 5

spring :
  # 环境 dev|test|prod
  profiles :
    active : dev
    #引入其他配置文件，例如ftpHX 未配置文件application-ftpHX.yml
    #include: ftpHX,ftpCloud
  servlet:
    multipart:
      #设置总上传的数据大小
      max-request-size: 100MB
      #单个文件大小
      maxFileSize : 30MB
        #xx 报错修改的地方
    max-connections: 200000
    max-http-post-size: 9000000
  #热部署模块
  devtools:
    restart:
      #热部署开关
      enabled: true
      #指定热部署的目录
      additional-paths: src/main/java
      #指定目录不更新
      exclude: test/**
  mvc:   #静态文件
    static-path-pattern : /static/**
  #模板引擎
  thymeleaf:
    model: HTML5
    prefix: classpath:/templates/
    suffix: .html
    #指定编码
    encoding: utf-8
    #禁用缓存 默认false
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    ssl: false
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 1000
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
  #静态文件地址
  web:
    resources:
      static-locations: classpath:/static/, classpath:/templates/
#mybatis:
#  #配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations : classpath*:mybatis/*/*.xml
#  #mybatis提供三种sql执行器，分别是SIMPLE、REUSE、BATCH。
#  executor-type : reuse
#  #搜索指定包别名
#  typeAliasesPackage : com.*.model
#  #该配置项就是指将带有下划线的表字段映射为驼峰格式的实体类属性。
#  configuration :
#    map-underscore-to-camel-case : true
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
oss:
  enable: true
  info: true
  path-style-access: false  #使用云OSS 需要关闭
  endpoint: http://127.0.0.1:9000 #对应上图 ③ 处配置
  access-key: minioadmin  # 上文创建的AK
  secret-key: minioadmin # 上文创建的SK
  bucket-name: v2-cloud  # 上文创建的桶名称

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

#chatGpt
chatgpt:
  #多个key英文逗号分割
  apiKey: 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
  #默认https://api.openai.com，如有自定义代理host，填写自定义代理host
  # 自定义代理host教程看https://github.com/Grt1228/chatgpt-java   ReadMe
  apiHost: https://api.openai-proxy.com/
