package com.fc.test.model.auto;

import java.io.Serializable;

public class UserMessageHistory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column us_message_train_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column us_message_train_record.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column us_message_train_record.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column us_message_train_record.create_time
     *
     * @mbg.generated
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column us_message_train_record.edit_time
     *
     * @mbg.generated
     */
    private Integer editTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table us_message_train_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column us_message_train_record.id
     *
     * @return the value of us_message_train_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column us_message_train_record.id
     *
     * @param id the value for us_message_train_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column us_message_train_record.user_id
     *
     * @return the value of us_message_train_record.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column us_message_train_record.user_id
     *
     * @param userId the value for us_message_train_record.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column us_message_train_record.content
     *
     * @return the value of us_message_train_record.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column us_message_train_record.content
     *
     * @param content the value for us_message_train_record.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column us_message_train_record.create_time
     *
     * @return the value of us_message_train_record.create_time
     *
     * @mbg.generated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column us_message_train_record.create_time
     *
     * @param createTime the value for us_message_train_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column us_message_train_record.edit_time
     *
     * @return the value of us_message_train_record.edit_time
     *
     * @mbg.generated
     */
    public Integer getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column us_message_train_record.edit_time
     *
     * @param editTime the value for us_message_train_record.edit_time
     *
     * @mbg.generated
     */
    public void setEditTime(Integer editTime) {
        this.editTime = editTime;
    }
}